namespace Core.Grafic
{
    internal static class GameOver
    {
        static private ConsoleColor borderColor = ConsoleColor.Red;

        static private ConsoleColor literColor = ConsoleColor.DarkRed;

        static private int borderDelay = 20;

        static private int literDelay = 1000;

        internal static List<GraficCell> CellList = new List<GraficCell>
        {
            new GraficCell(0, 0, borderColor, borderDelay),
            new GraficCell(1, 0, borderColor, borderDelay),
            new GraficCell(-1, 0, borderColor, 0),
            new GraficCell(2, 0, borderColor, borderDelay),
            new GraficCell(-2, 0, borderColor, 0),
            new GraficCell(3, 0, borderColor, borderDelay),
            new GraficCell(-3, 0, borderColor, 0),
            new GraficCell(4, 0, borderColor, borderDelay),
            new GraficCell(-4, 0, borderColor, 0),
            new GraficCell(5, 0, borderColor, borderDelay),
            new GraficCell(-5, 0, borderColor, 0),
            new GraficCell(6, 0, borderColor, borderDelay),
            new GraficCell(-6, 0, borderColor, 0),
            new GraficCell(7, 0, borderColor, borderDelay),
            new GraficCell(-7, 0, borderColor, 0),
            new GraficCell(8, 0, borderColor, borderDelay),
            new GraficCell(-8, 0, borderColor, 0),
            new GraficCell(9, 0, borderColor, borderDelay),
            new GraficCell(-9, 0, borderColor, 0),
            new GraficCell(10, 0, borderColor, borderDelay),
            new GraficCell(-10, 0, borderColor, 0),
            new GraficCell(11, 0, borderColor, borderDelay),
            new GraficCell(-11, 0, borderColor, 0),
            new GraficCell(12, 0, borderColor, borderDelay),
            new GraficCell(-12, 0, borderColor, 0),
            new GraficCell(13, 0, borderColor, borderDelay),
            new GraficCell(-13, 0, borderColor, 0),
            new GraficCell(13, 0, borderColor, borderDelay),
            new GraficCell(-13, 0, borderColor, 0),
            new GraficCell(14, 0, borderColor, borderDelay),
            new GraficCell(-14, 0, borderColor, 0),
            new GraficCell(15, 0, borderColor, borderDelay),
            new GraficCell(-15, 0, borderColor, 0),
            new GraficCell(16, 0, borderColor, borderDelay),
            new GraficCell(-16, 0, borderColor, 0),
            new GraficCell(17, 0, borderColor, borderDelay),
            new GraficCell(-17, 0, borderColor, 0),
            new GraficCell(18, 0, borderColor, borderDelay),
            new GraficCell(-18, 0, borderColor, 0),
            new GraficCell(19, 0, borderColor, borderDelay),
            new GraficCell(-19, 0, borderColor, 0),
            new GraficCell(20, 0, borderColor, borderDelay),
            new GraficCell(-20, 0, borderColor, 0),
            new GraficCell(21, 0, borderColor, borderDelay),
            new GraficCell(-21, 0, borderColor, 0),
            new GraficCell(22, 0, borderColor, borderDelay),
            new GraficCell(-22, 0, borderColor, 0),
            new GraficCell(23, 0, borderColor, borderDelay),
            new GraficCell(-23, 0, borderColor, 0),
            new GraficCell(24, 0, borderColor, borderDelay),
            new GraficCell(-24, 0, borderColor, 0),

            new GraficCell(25, 1, borderColor, borderDelay),
            new GraficCell(-25, 1, borderColor, 0),
            new GraficCell(25, 2, borderColor, borderDelay),
            new GraficCell(-25, 2, borderColor, 0),
            new GraficCell(25, 3, borderColor, borderDelay),
            new GraficCell(-25, 3, borderColor, 0),
            new GraficCell(25, 4, borderColor, borderDelay),
            new GraficCell(-25, 4, borderColor, 0),
            new GraficCell(25, 5, borderColor, borderDelay),
            new GraficCell(-25, 5, borderColor, 0),
            new GraficCell(25, 6, borderColor, borderDelay),
            new GraficCell(-25, 6, borderColor, 0),
            new GraficCell(25, 7, borderColor, borderDelay),
            new GraficCell(-25, 7, borderColor, 0),
            new GraficCell(25, 8, borderColor, borderDelay),
            new GraficCell(-25, 8, borderColor, 0),

            new GraficCell(24, 9, borderColor, borderDelay),
            new GraficCell(-24, 9, borderColor, 0),
            new GraficCell(23, 9, borderColor, borderDelay),
            new GraficCell(-23, 9, borderColor, 0),
            new GraficCell(22, 9, borderColor, borderDelay),
            new GraficCell(-22, 9, borderColor, 0),
            new GraficCell(21, 9, borderColor, borderDelay),
            new GraficCell(-21, 9, borderColor, 0),
            new GraficCell(20, 9, borderColor, borderDelay),
            new GraficCell(-20, 9, borderColor, 0),
            new GraficCell(19, 9, borderColor, borderDelay),
            new GraficCell(-19, 9, borderColor, 0),
            new GraficCell(18, 9, borderColor, borderDelay),
            new GraficCell(-18, 9, borderColor, 0),
            new GraficCell(17, 9, borderColor, borderDelay),
            new GraficCell(-17, 9, borderColor, 0),
            new GraficCell(16, 9, borderColor, borderDelay),
            new GraficCell(-16, 9, borderColor, 0),
            new GraficCell(15, 9, borderColor, borderDelay),
            new GraficCell(-15, 9, borderColor, 0),
            new GraficCell(14, 9, borderColor, borderDelay),
            new GraficCell(-14, 9, borderColor, 0),
            new GraficCell(13, 9, borderColor, borderDelay),
            new GraficCell(-13, 9, borderColor, 0),
            new GraficCell(12, 9, borderColor, borderDelay),
            new GraficCell(-12, 9, borderColor, 0),
            new GraficCell(11, 9, borderColor, borderDelay),
            new GraficCell(-11, 9, borderColor, 0),
            new GraficCell(10, 9, borderColor, borderDelay),
            new GraficCell(-10, 9, borderColor, 0),
            new GraficCell(9, 9, borderColor, borderDelay),
            new GraficCell(-9, 9, borderColor, 0),
            new GraficCell(8, 9, borderColor, borderDelay),
            new GraficCell(-8, 9, borderColor, 0),
            new GraficCell(7, 9, borderColor, borderDelay),
            new GraficCell(-7, 9, borderColor, 0),
            new GraficCell(6, 9, borderColor, borderDelay),
            new GraficCell(-6, 9, borderColor, 0),
            new GraficCell(5, 9, borderColor, borderDelay),
            new GraficCell(-5, 9, borderColor, 0),
            new GraficCell(4, 9, borderColor, borderDelay),
            new GraficCell(-4, 9, borderColor, 0),
            new GraficCell(3, 9, borderColor, borderDelay),
            new GraficCell(-3, 9, borderColor, 0),
            new GraficCell(2, 9, borderColor, borderDelay),
            new GraficCell(-2, 9, borderColor, 0),
            new GraficCell(1, 9, borderColor, borderDelay),
            new GraficCell(-1, 9, borderColor, 0),
            new GraficCell(0, 9, borderColor, literDelay),

            new GraficCell(-23, 3, literColor),
            new GraficCell(-23, 4, literColor),
            new GraficCell(-23, 5, literColor),
            new GraficCell(-23, 6, literColor),
            new GraficCell(-22, 2, literColor),
            new GraficCell(-21, 2, literColor),
            new GraficCell(-20, 2, literColor),
            new GraficCell(-22, 7, literColor),
            new GraficCell(-21, 7, literColor),
            new GraficCell(-20, 7, literColor),
            new GraficCell(-20, 6, literColor),
            new GraficCell(-20, 5, literColor),
            new GraficCell(-21, 5, literColor),

            new GraficCell(-18, 3, literColor),
            new GraficCell(-18, 4, literColor),
            new GraficCell(-18, 5, literColor),
            new GraficCell(-18, 6, literColor),
            new GraficCell(-18, 7, literColor),
            new GraficCell(-17, 2, literColor),
            new GraficCell(-17, 6, literColor),
            new GraficCell(-16, 2, literColor),
            new GraficCell(-16, 6, literColor),
            new GraficCell(-15, 3, literColor),
            new GraficCell(-15, 4, literColor),
            new GraficCell(-15, 5, literColor),
            new GraficCell(-15, 6, literColor),
            new GraficCell(-15, 7, literColor),

            new GraficCell(-13, 3, literColor),
            new GraficCell(-13, 4, literColor),
            new GraficCell(-13, 5, literColor),
            new GraficCell(-13, 6, literColor),
            new GraficCell(-13, 7, literColor),
            new GraficCell(-12, 2, literColor),
            new GraficCell(-11, 3, literColor),
            new GraficCell(-10, 4, literColor),
            new GraficCell(-9, 3, literColor),
            new GraficCell(-8, 2, literColor),
            new GraficCell(-7, 3, literColor),
            new GraficCell(-7, 4, literColor),
            new GraficCell(-7, 5, literColor),
            new GraficCell(-7, 6, literColor),
            new GraficCell(-7, 7, literColor),

            new GraficCell(-5, 3, literColor),
            new GraficCell(-5, 4, literColor),
            new GraficCell(-5, 5, literColor),
            new GraficCell(-5, 6, literColor),
            new GraficCell(-4, 2, literColor),
            new GraficCell(-4, 4, literColor),
            new GraficCell(-4, 7, literColor),
            new GraficCell(-3, 2, literColor),
            new GraficCell(-3, 4, literColor),
            new GraficCell(-3, 7, literColor),
            new GraficCell(-2, 2, literColor),
            new GraficCell(-2, 4, literColor),
            new GraficCell(-2, 7, literColor, literDelay),

            new GraficCell(3, 3, literColor),
            new GraficCell(3, 4, literColor),
            new GraficCell(3, 5, literColor),
            new GraficCell(3, 6, literColor),
            new GraficCell(4, 2, literColor),
            new GraficCell(5, 2, literColor),
            new GraficCell(4, 7, literColor),
            new GraficCell(5, 7, literColor),
            new GraficCell(6, 3, literColor),
            new GraficCell(6, 4, literColor),
            new GraficCell(6, 5, literColor),
            new GraficCell(6, 6, literColor),


            new GraficCell(8, 2, literColor),
            new GraficCell(8, 3, literColor),
            new GraficCell(8, 4, literColor),
            new GraficCell(8, 5, literColor),
            new GraficCell(8, 6, literColor),
            new GraficCell(9, 7, literColor),
            new GraficCell(10, 7, literColor),
            new GraficCell(11, 7, literColor),
            new GraficCell(12, 2, literColor),
            new GraficCell(12, 3, literColor),
            new GraficCell(12, 4, literColor),
            new GraficCell(12, 5, literColor),
            new GraficCell(12, 6, literColor),

            new GraficCell(14, 3, literColor),
            new GraficCell(14, 4, literColor),
            new GraficCell(14, 5, literColor),
            new GraficCell(14, 6, literColor),
            new GraficCell(15, 2, literColor),
            new GraficCell(15, 4, literColor),
            new GraficCell(15, 7, literColor),
            new GraficCell(16, 2, literColor),
            new GraficCell(16, 4, literColor),
            new GraficCell(16, 7, literColor),
            new GraficCell(17, 2, literColor),
            new GraficCell(17, 4, literColor),
            new GraficCell(17, 7, literColor),

            new GraficCell(19, 2, literColor),
            new GraficCell(19, 3, literColor),
            new GraficCell(19, 4, literColor),
            new GraficCell(19, 5, literColor),
            new GraficCell(19, 6, literColor),
            new GraficCell(19, 7, literColor),
            new GraficCell(20, 2, literColor),
            new GraficCell(20, 5, literColor),
            new GraficCell(21, 2, literColor),
            new GraficCell(21, 5, literColor),
            new GraficCell(22, 2, literColor),
            new GraficCell(22, 5, literColor),
            new GraficCell(22, 6, literColor),
            new GraficCell(23, 3, literColor),
            new GraficCell(23, 4, literColor),
            new GraficCell(23, 7, literColor),

        };


    }
}
